
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/



#include <iostream>
#include <queue>

using namespace std;

int main() {
    queue <int> fibNumberQueue;
    int sumOfAllEvenFib = 0;

    fibNumberQueue.push(1);
    fibNumberQueue.push(2);

    while(fibNumberQueue.back() <= 4000000)
    {
        if(fibNumberQueue.back() % 2 == 0){
            sumOfAllEvenFib += fibNumberQueue.back();
        }

        fibNumberQueue.push((fibNumberQueue.front() + fibNumberQueue.back()));
        fibNumberQueue.pop();

    }

    cout << "The sum of the even-valued terms fibonacci numbers: " << sumOfAllEvenFib << endl;
}